.\" -*- nroff -*-
.\" $Id: swup.1,v 1.4 2001/03/13 14:01:07 olafb Exp $
.\" Copyright (c) Trustix AS 2001
.TH SWUP 1 "Jan 11, 2001"
.SH NAME
swup \- SoftWare UPdater
.SH SYNOPSIS
.B swup [operation] [options]
.SH DESCRIPTION
.B swup
is short for ``Software Updater''. It is an
extension to existing software package systems to facilitate automatic
install and upgrade.
.SH OPERATIONS
.IP "--help"
Print brief usage information.
.IP "--version"
Print version and copyright information.
.IP "--list-latest"
List latest version of packages available.
.IP "--list-new"
Like list-latest, but only list new packages that are not installed.
.IP "--install"
Install modus. Must be used together with a --package-* switch.
.IP "--upgrade"
Upgrade modus. Optional --package-* switch can be supplied.
.IP "--import-key"
Import a gpg public key. Takes one argument
.I filename
which is a file containing gpg public keys to be imported to keyring.
.IP "--list-keys"
List all public keys in gpg keyring.
.SH OPTIONS
.IP "--verbose"
Write somewhat more verbose messages to stdout.
.IP "--quiet"
Don't write status messages to stdout. Overrides --verbose.
.IP "--silent"
Be quiet and do not write any messages other than errors. Overrides
--verbose and --quiet.
.IP "--no-flush-cache"
Do not delete cached files after they are installed. Default is to
flush cache.
.IP "--poll-only"
Only poll for upgrades. This will print pending upgrades, but will not
try to resolve additional dependencies introduced by an upgrade. Used
in conjunction with --upgrade.
.IP "--download-only"
Run as usual, download packages, but do not install. Implies --no-flush-cache.
.IP "--save-to dir"
Save a copy of all downloaded software packages to dir.
.IP "--config-file file"
Use an alternate system wide
.I config-file
instead of
.I /etc/swup/swup.conf
File should not contain non-alphanumeric characters.
.IP "--repository-URI URI"
Use Uniform Resource Allocator to file that contains a list of latest
packages.  This will override the list of default URIs in
configuration file. Protocols
.I file,
.I http,
and
.I ftp
are supported.
.IP "--package-URI URI [URI]"
Use URIs to SPI for packages and try to install/upgrade these
specific packages.
.IP "--package-URI-file [...]"
Same as above, except that the URI-list is read from a file of newline
separated URIs.
.IP "--package name [...]"
Install/upgrade packages with name
.I name.
The name is shortname for the package. E.g. vim, and not
vim-5.6-3tr.i586.rpm.
.IP "--package-file file"
Same as above, except that the package names are given in a file,
separated by newline.
.IP "--gnupg-dir dir"
Use
.I dir
as directory where Gnu Privacy Guard files are stored, instead of the
default
.I /etc/swup/gnupg/
.SH FILES
.I /etc/swup/swup.conf
.RS
System wide configuration file for swup. See
.BR swup(5)
for more details.
.RE
.I /etc/swup/gnupg
.RS
Directory where Gnu Privacy Guard files are stored.
.SH DIAGNOSTICS
.I swup
will write messages to stdout and stderr. Upon completion a standard
exit code is returned to the calling shell. swup returns 0 for a
succesfull execution, 1 for general error and 2 for command line
syntax error.
.SH BUGS
None known.
.SH AUTHOR
Olaf Trygve Berglihn <olafb@trustix.com>


