.\" -*- nroff -*-
.\" $Id: swup.5,v 1.4 2001/03/20 11:50:10 olafb Exp $
.\" Copyright (c) Trustix AS 2000
.TH SWUP 5 "Mar 20, 2001"
.SH NAME
swup \- format of the configuration file
.SH DESCRIPTION
.B swup.conf
is a configuration file for the swup program.
.SH FILE FORMAT
.PP
The configuration file consists of `name = value' and section entries
with continuations in the style of RFC 822. Sections are specified by
section name, and delimited by curly braces. Sections contain `name =
value' entries. Lines begining with a hash, "#", will be ignored. The
"#"-symbol can not be used for comments on a line with a variable
definition. Example:

option = value

section {
  option1 = value
  option2 = value
  }
.SH REGEXP SYNTAX
The regexp syntax is similar to what egrep use. See 
.B "grep(1)"
.SH VARIABLES
.IP logfile
file in which the swup log is stored.
.IP gnupgdir
where gnupg public keyring and such is found. Default is
/etc/swup/gnupg
.IP save_to
directory in were a copy of all downloaded software packages should be
saved. If variable is empty or undefined, a copies will not be saved.
.IP dependency_maxdepth
.I Not supported yet.
Sets the maximum number of recursive requirements allowed. I.e. swup
will complain if a package requires packages that in turn require
packages, etc. to a depth of dependency_maxdepth. Valid values are 0 or
greater, default is 5.
.IP cachedir
directory to which downloaded files are stored.
.IP tmpdir
directory to which files are stored temporarily under the download
process.
.IP flush_cache 
["yes"|"no"] -
delete files in cache after a successful upgrade or install. Default
is "yes".
.IP "interactive_logged"
["yes"|"no"] -
Write to logfile if session is run from a tty. Default is "yes".
.IP sites
Section that provides information about where to get information about
software. A sites section is specified by

site {
  priority = <unsigned int>
  location = <URI>
  regexp = <regular expression>
  }
.RS
.PP
.I priority 
- an unsigned integer specifying what priority the site has. 0 is the
greatest priority, with increasing numbers having less priority. Two
sites can have the same priority, but only the first one that works at
that priority level will be used, i.e. sites with same priority can be
alternates.
.PP
.I location
- the uniformed resource identifier to the file in which
SPI-information can be found. Normally that would a file called
\'latest.rdf\'.
.PP
.I regexp
- the regular expression of which packages at the site that are
allowed to be used for install or upgrades. See "REGEXP SYNTAX" above.
.RE
.IP "exclude/include rules"
Rules that control which packages can be upgraded. The rules are
regular expressions and are used as search rules. I.e. a rule
"kernel" will match the string
`kernel', where as "kernel-.*2\\.2\\.12" will match both
`kernel-source-2.2.12-20', `kernel-headers-2.2.12-20' and
`kernel-2.2.12-20'.
.RS
.PP
There are rules on two levels: `package' and `group'.  `Package' refer
to software package name, `group' refers to software group to which
package is classified (dependent on packaging system). The precedence
of the rules are in the order package, group. I.e. a rule on package
level will override group An exclude rule also has higher precidence
than an include rule. See "REGEXP SYNTAX" above for the syntax of the
rules.
.RS
.I exclude_pkg_regexp
- deny upgrade of all packages whose name contains a substring that
will match regexp.
.PP
.I include_pkg_regexp
- allow upgrade of all packages whose name contains a substring that
will match regexp.
.PP
.I exclude_group_regexp
- deny upgrade of all packages whose group name contains a substring
that will match regexp.
.PP
.I include_group_regexp
- allow upgrade of all packages whose group name contains a substring
that will
match regexp.
.PP
.RE
.SH FILES
.I /etc/swup/swup.conf
.RS
System wide configuration file for swup.
.RE
.SH AUTHOR
Olaf Trygve Berglihn <olafb@trustix.com>


